version: '3.9'

services:
  database:
    image: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_farmagedon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '3030:5432'

  farmagedon:
    image: farmagedon
    depends_on:
      - database
    environment:
      PSQL_HOST: database
    ports:
      - '3000:3000'
